刪掉backenv 檔案
Bosh-Kuo/Database-2022-Fall pull request #13
Opened 2022-12-10 17:34 UTC by codax0421

# Summary

#12

2022-12-11 08:03 UTC, Bosh-Kuo requested changes
感謝～
另外想麻煩你在 vscode 裝 Prettier - Code formatter (前端自動排版套件)
後端我已經有安裝 black formatter

麻煩幫我在 vscode 的設定黨中加入這幾行

`
"[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },  
`
`
"[python]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
  },
  "python.formatting.provider": "black",
`
這樣你存檔或是按下排版快捷鍵的時候就會自動排版

2022-12-11 08:03 UTC, Bosh-Kuo commented on e_commerce_backend/e_commerce_backend/urls.py
> +    path("category/",views.category_list)
這幾行搬到 app/urls.py 比較好 ～

2022-12-11 08:03 UTC, Bosh-Kuo commented on e_commerce_backend/e_commerce_backend/urls.py
>      path("admin/", admin.site.urls),
```suggestion
    path("api/",include('app.urls')),
```

2022-12-11 08:03 UTC, Bosh-Kuo commented on e_commerce_frontend/src/components/pages/axios.js
> +            baseURL: baseURL || 'http://127.0.0.1:8000', //JSON-Server端口位置
```suggestion
            baseURL: baseURL || 'http://127.0.0.1:8000/api', //JSON-Server端口位置
```

2022-12-11 08:03 UTC, Bosh-Kuo commented on e_commerce_frontend/src/components/pages/axios.js
> +export default axios();
axios.js 我建議放到 components 資料夾外面，component 資料夾下單純放畫面組件

2022-12-11 08:13 UTC, Bosh-Kuo commented on e_commerce_frontend/src/components/pages/Home.js
> +             <Card style={{ width: "300px", margin:"10px"}} onClick={(e)=>navigateToProduct(e,product.id ,product.name)} value={product.id} key ={product.id}
```suggestion
             <Card style={{ width: "300px", margin:"10px"}}  value={product.id} key ={product.id}
```

2022-12-11 08:14 UTC, Bosh-Kuo commented on e_commerce_frontend/src/components/pages/Home.js
> +               />
點圖片再 navigate 到 product 頁面～
```suggestion
               <img
                 alt={product.alt}
                 src={"http://127.0.0.1:8000/"+product.image}
                 onClick={(e)=>navigateToProduct(e,product.id ,product.name)}
               />
```

2022-12-11 09:03 UTC, codax0421 commented
了解，稍後改一改，感謝！

2022-12-14 09:44 UTC, codax0421 commented
東西都改好了，只是不知道black formatter 對我的backend好像沒起作用

2022-12-15 07:24 UTC, Bosh-Kuo commented
你看看你的vscode 右下角的認定的python 環境是不是你現在在用的環境，不是的話點他後再選你現在在用的環境應該就有了～
![截圖 2022-12-15 下午3 20 23](https://user-images.githubusercontent.com/79684268/207798376-41f8af9b-141e-40b9-a7ea-bc3a37e330b3.png)

2022-12-15 07:25 UTC, Bosh-Kuo approved these changes

2022-12-15 07:27 UTC, merged

2022-12-15 07:30 UTC, Bosh-Kuo commented
black formatter 你之後再試試看，其他的部分應該沒問題～ 我先 merge 了，辛苦了～